/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uastugas;

/**
 *
 * @author Lenovo
 */
public class motivasi extends javax.swing.JFrame {

    /**
     * Creates new form cerpen
     */
    public motivasi() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("1. “Semua stres, kecemasan, depresi, disebabkan kita mengabaikan siapa diri kita dan mulai hidup untuk menyenangkan orang lain.” −Paulo Coelho.\n\n2. “Penyakit mental terjadi ketika kesehatan mental kita dikompromikan atau diabaikan begitu lama sehingga memengaruhi kemampuan kita untuk berfungsi dalam kehidupan sehari-hari.” −Kati Morton.\n\n3. “Aku percaya cara terbaik untuk mengelola pikiran adalah dengan mendidik diri kita sendiri terlebih dahulu. Kita perlu memahami sepenuhnya perasaan penyakit mental terhadap seseorang sebelum kita membicarakannya dengan serius.” −Kati Morton.\n\n4. “Penyakit mental bukanlah hal yang memalukan, tetapi stigma dan bias yang mempermalukan kita semua.” −Bill Clinton.\n\n5. \"Kadang-kadang kamu bangun dari tempat tidur di pagi hari dan kamu berpikir, aku tidak akan berhasil. Namun, kamu tertawa di dalam hati mengingat semua waktu yang kamu rasakan seperti itu.\" −Charles Bukowski.\n\n6. “Aku menemukan bahwa dengan depresi, salah satu hal terpenting yang dapat kamu sadari adalah bahwa kamu tidak sendiri. Kamu bukan yang pertama melewatinya. Kamu juga tidak akan menjadi yang terakhir melewatinya.” –Dwayne “The Rock” Johnson.\n\n7. “Ingat saja, kamu tidak sendirian. Pada kenyataannya, kamu berada di tempat yang sangat biasa dengan jutaan orang lain. Kita perlu saling membantu dan terus berjuang untuk mencapai tujuan kita.” —Mike Moreno.\n\n8. “Perasaan ini akan berlalu. Ketakutan itu nyata tetapi bahayanya tidak.” −Cammie McGovern.\n\n9. \"Perawatan diri adalah bagaimana kamu mengambil kembali kekuatan kamu.\" −Lalah Delia.\n\n10. \"Satu retakan kecil bukan berarti kamu hancur. Itu berarti kamu sedang diuji dan kamu tidak hancur.\" −Linda Poindexter.");
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 77, 715, 402));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MOTIVASI MENTAL HEALTH!");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 33, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 509, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Downloads\\yttt.jpg")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-220, 0, 1130, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    new menuutama().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(motivasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(motivasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(motivasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(motivasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new motivasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
