/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uastugas;

/**
 *
 * @author Lenovo
 */
public class solusi extends javax.swing.JFrame {

    /**
     * Creates new form panduan
     */
    public solusi() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("-Waham atau delusi, yaitu meyakini sesuatu yang tidak nyata atau tidak sesuai dengan fakta yang sebenarnya\n-Halusinasi, yaitu sensasi ketika seseorang melihat, mendengar, atau merasakan sesuatu yang sebenarnya tidak nyata\n-Suasana hati yang berubah-ubah dalam periode-periode tertentu\n-Perasaan sedih yang berlangsung hingga berminggu-minggu, bahkan berbulan-bulan\n-Perasaan cemas atau takut yang berlebihan dan terus menerus, sampai mengganggu aktivitas sehari-hari\n-Gangguan makan, misalnya merasa takut berat badan bertambah, cenderung memuntahkan makanan, atau makan dalam jumlah banyak\n-Perubahan pada pola tidur, seperti mudah mengantuk dan tertidur, sulit tidur, serta gangguan pernapasan dan kaki gelisah saat tidur\n-Kecanduan nikotin atau alkohol, serta penyalahgunaan NAPZA\n-Marah berlebihan sampai mengamuk dan melakukan tindak kekerasan\n-Perilaku yang tidak wajar, seperti teriak-teriak tidak jelas, berbicara dan tertawa sendiri, serta keluar rumah dalam kondisi telanjang.");
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 806, -1));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("Faktor biologis atau disebut juga gangguan mental organik\n-Gangguan pada fungsi sel saraf di otak\n-Infeksi, misalnya akibat bakteri Streptococcus \n-Kerusakan otak akibat terbentur atau kecelakaan\n-Kekurangan oksigen pada otak bayi saat proses persalinan\n-Riwayat gangguan mental pada orang tua atau keluarga\n-Penyalahgunaan NAPZA, seperti heroin dan kokain, dalam jangka panjang\n-Kekurangan nutrisi\nFaktor psikologis\n-Peristiwa traumatik, seperti kekerasan dan pelecehan seksual\n-Kehilangan orang tua atau disia-siakan di masa kecil\n-Kurang mampu bergaul dengan orang lain\n-Perceraian atau ditinggal mati oleh pasangan\n-Perasaan rendah diri, tidak mampu, marah, atau kesepian");
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 48, 806, -1));

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jTextArea3.setText("Berpartisipasi aktif dalam pergaulan dan aktivitas yang disenangi\nBerbagi dengan teman dan keluarga saat menghadapi masalah\nBerolahraga rutin, makan teratur, dan mengelola stres dengan baik\nMenetapkan jadwal tidur dan bangun tidur yang teratur setiap harinya\nMengikuti latihan untuk menenangkan pikiran atau relaksasi, misalnya dengan meditasi dan yoga\nTidak merokok dan tidak menggunakan NAPZA\nMembatasi konsumsi minuman beralkohol dan minuman berkafein\nMengonsumsi obat yang diresepkan dokter sesuai dosis dan aturan pakai\nMemeriksakan diri ke dokter atau psikolog untuk menjalani skrining awal kesehatan mental atau bila muncul gejala gangguan mental");
        jScrollPane3.setViewportView(jTextArea3);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 217, 806, -1));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PENYEBAB");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 11, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SOLUSI");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 185, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CONTOH");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Downloads\\yttt.jpg")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-230, 0, 1140, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    new menuutama().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(solusi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(solusi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(solusi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(solusi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new solusi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    // End of variables declaration//GEN-END:variables
}
