/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uastugas;


import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.DriverManager;
import java.sql.Statement;


/**
 *
 * @author Lenovo
 */
public class tes extends javax.swing.JFrame {
   public Connection con;
   public Statement stat;
   public ResultSet rs;
   


    /**
     * Creates new form tes
     */
    public tes() {
        initComponents();
        this.clearData();
        setLocationRelativeTo(this);

    }
   
    final void clearData()
    {
        q1.setSelectedItem("");
        q2.setSelectedItem("");
        q3.setSelectedItem("");
        q4.setSelectedItem("");
        q5.setSelectedItem("");
        q6.setSelectedItem("");
        q7.setSelectedItem("");
        q8.setSelectedItem("");
        q9.setSelectedItem("");
        q10.setSelectedItem("");
        tes.setText("");;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tes = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        q1 = new javax.swing.JComboBox<>();
        q2 = new javax.swing.JComboBox<>();
        q3 = new javax.swing.JComboBox<>();
        q4 = new javax.swing.JComboBox<>();
        q5 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        answer = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        answer1 = new javax.swing.JButton();
        answer2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        q6 = new javax.swing.JComboBox<>();
        q7 = new javax.swing.JComboBox<>();
        q8 = new javax.swing.JComboBox<>();
        q9 = new javax.swing.JComboBox<>();
        q10 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tes.setColumns(20);
        tes.setRows(5);
        jScrollPane1.setViewportView(tes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, 250, 131));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Apakah kamu mudah tersinggung terhadap orang lain?");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 28, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Apakah kamu menyukai keramaian?");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Apakah kamu merasa senang berkomunikasi dengan orang terdekat?");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Apakah kamu bisa menikmati kegiatan atau pekerjaan sehari-harimu?");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Apakah kamu suka membandingkan dirimu terhadap orang lain?");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        q1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        q1.setForeground(new java.awt.Color(255, 51, 51));
        q1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "0" }));
        getContentPane().add(q1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 30, 60, -1));

        q2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        q2.setForeground(new java.awt.Color(255, 0, 51));
        q2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "0" }));
        getContentPane().add(q2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 60, 60, -1));

        q3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        q3.setForeground(new java.awt.Color(255, 0, 0));
        q3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "0" }));
        getContentPane().add(q3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 90, 60, -1));

        q4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        q4.setForeground(new java.awt.Color(255, 0, 0));
        q4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "0" }));
        getContentPane().add(q4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 120, 60, -1));

        q5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        q5.setForeground(new java.awt.Color(255, 0, 0));
        q5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "0" }));
        q5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q5ActionPerformed(evt);
            }
        });
        getContentPane().add(q5, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 300, 60, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("HASIL TEST ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, -1, -1));

        answer.setBackground(new java.awt.Color(255, 255, 51));
        answer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        answer.setText("CEK HASIL");
        answer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerActionPerformed(evt);
            }
        });
        getContentPane().add(answer, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 390, 100, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("QUIS TEST");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 11, -1, -1));

        answer1.setBackground(new java.awt.Color(255, 255, 0));
        answer1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        answer1.setText("BACK");
        answer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer1ActionPerformed(evt);
            }
        });
        getContentPane().add(answer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 490, 100, -1));

        answer2.setBackground(new java.awt.Color(255, 255, 0));
        answer2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        answer2.setText("CEK KET");
        answer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer2ActionPerformed(evt);
            }
        });
        getContentPane().add(answer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 440, 100, -1));

        jLabel8.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Apakah kamu menyukai kegiatan berolahraga?");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Apakah kamu merasa tenang dan damai?");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Apakah kamu suka berkumpul dengan keluarga?");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        q6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        q6.setForeground(new java.awt.Color(255, 0, 0));
        q6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "0" }));
        q6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q6ActionPerformed(evt);
            }
        });
        getContentPane().add(q6, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 150, 60, -1));

        q7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        q7.setForeground(new java.awt.Color(255, 0, 0));
        q7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "0" }));
        q7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q7ActionPerformed(evt);
            }
        });
        getContentPane().add(q7, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 180, 60, -1));

        q8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        q8.setForeground(new java.awt.Color(255, 0, 0));
        q8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "0" }));
        q8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q8ActionPerformed(evt);
            }
        });
        getContentPane().add(q8, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 240, 60, -1));

        q9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        q9.setForeground(new java.awt.Color(255, 0, 0));
        q9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "0" }));
        q9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q9ActionPerformed(evt);
            }
        });
        getContentPane().add(q9, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 210, 60, -1));

        q10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        q10.setForeground(new java.awt.Color(255, 0, 0));
        q10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "0" }));
        q10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q10ActionPerformed(evt);
            }
        });
        getContentPane().add(q10, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 270, 60, -1));

        jLabel12.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Apakah kamu mudah menjalin pertemanan?");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Apakah kamu menyukai lingkungan sekitarmu?");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        jLabel18.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("0 = TIDAK");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        jLabel19.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("ATURAN PENGISIAN");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        jLabel20.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("1 = YA");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Downloads\\yttt.jpg")); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-280, -110, 1190, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void q5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q5ActionPerformed

    private void answerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerActionPerformed
           // TODO add your handling code here:
         try{
               if (q1.getSelectedItem().equals("")|| q2.getSelectedItem().equals("")|| q3.getSelectedItem().equals("")|| q4.getSelectedItem().equals("")|| q5.getSelectedItem().equals("")||
                   q6.getSelectedItem().equals("")||q7.getSelectedItem().equals("")||q8.getSelectedItem().equals("")||q9.getSelectedItem().equals("")||q10.getSelectedItem().equals("")||tes.getText().equals("")){
            }else{
                Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/tugaspbo","root","");
            stat = con.createStatement();
             String simpan = "insert into quis3 values ('"+q1.getSelectedItem()+"','"+q2.getSelectedItem()+"','"+q3.getSelectedItem()+"','"+q4.getSelectedItem()+"','" +q5.getSelectedItem()+"','"
                    +q6.getSelectedItem()+"','"+q7.getSelectedItem()+"','"+q8.getSelectedItem()+"','"+q9.getSelectedItem()+"','"+q10.getSelectedItem()+"','"+tes.getText()+"')";
             stat=con.createStatement(); 
             int SA = stat.executeUpdate(simpan);
             JOptionPane.showMessageDialog(this,"SUCCES TEST");
            }
        int tanya1 = Integer.parseInt((String)q1.getSelectedItem());
        int tanya2 = Integer.parseInt((String)q2.getSelectedItem());
        int tanya3 = Integer.parseInt((String)q3.getSelectedItem());
        int tanya4 = Integer.parseInt((String)q4.getSelectedItem());
        int tanya5 = Integer.parseInt((String)q5.getSelectedItem());
        int tanya6 = Integer.parseInt((String)q6.getSelectedItem());
        int tanya7 = Integer.parseInt((String)q7.getSelectedItem());
        int tanya8 = Integer.parseInt((String)q8.getSelectedItem());
        int tanya9 = Integer.parseInt((String)q9.getSelectedItem());
        int tanya10 = Integer.parseInt((String)q10.getSelectedItem());
        int total = tanya1+tanya2+tanya3+tanya4+tanya5+tanya6+tanya7+tanya8+tanya9+tanya10;
        String hasil=null;
        switch (total) {
            case 10:
            hasil = "PRESNTASE HEALTH : 100%";
            break;
            case 9:
            hasil = "PRESENTASE HEALTH : 90%";
            break;
            case 8:
            hasil = "PRESENTASE HEALTH : 80%";
            break;
            case 7:
            hasil = "PRESENTASE HEALTH : 70%";
            break;
            case 6:
            hasil = "PRESENTASE HEALTH : 60%";
            break;
             case 5:
            hasil = "PRESENTASE HEALTH : 50%";
            break;
             case 4:
            hasil = "PRESENTASE HEALTH : 40%";
            break;
             case 3:
            hasil = "PRESENTASE HEALTH : 30%";
            break;
             case 2:
            hasil = "PRESENTASE HEALTH : 20%";
            break;
             case 1:
            hasil = "PRESENTASE HEALTH : 10%";
            break;
            default:
            hasil = "PRESENTASE HEALTH : 0%";
            break;
        }
        tes.setText(hasil);
          
           

        }catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane,e);
        }
    }//GEN-LAST:event_answerActionPerformed

    private void answer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer1ActionPerformed
    this.setVisible(false);
    new menuutama().setVisible(true);
        // TODO add your handling code here:
        
    }//GEN-LAST:event_answer1ActionPerformed

    private void answer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer2ActionPerformed
    this.setVisible(false);
    new keterangan().setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_answer2ActionPerformed

    private void q6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q6ActionPerformed

    private void q7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q7ActionPerformed

    private void q8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q8ActionPerformed

    private void q9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q9ActionPerformed

    private void q10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton answer;
    private javax.swing.JButton answer1;
    private javax.swing.JButton answer2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> q1;
    private javax.swing.JComboBox<String> q10;
    private javax.swing.JComboBox<String> q2;
    private javax.swing.JComboBox<String> q3;
    private javax.swing.JComboBox<String> q4;
    private javax.swing.JComboBox<String> q5;
    private javax.swing.JComboBox<String> q6;
    private javax.swing.JComboBox<String> q7;
    private javax.swing.JComboBox<String> q8;
    private javax.swing.JComboBox<String> q9;
    private javax.swing.JTextArea tes;
    // End of variables declaration//GEN-END:variables
}
